"""empty message

Revision ID: 56593c3fee64
Revises: db76f71e14d4
Create Date: 2023-05-10 17:35:23.525227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56593c3fee64'
down_revision = 'db76f71e14d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
